name: C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW
        run: choco install mingw -y

      - name: Add MinGW to PATH
        run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

      - name: Check g++
        run: g++ --version

      - name: Build
        run: g++ main.cpp -o main.exe

      - name: Run
        run: .\main.exe